version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASS:-mypassword}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-myuser} -d ${DB_NAME:-mydatabase}"]
      interval: 5s
      timeout: 5s
      retries: 5

  svc-subman:
    build:
      context: .
    container_name: svc-subman
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-myuser}
      DB_PASS: ${DB_PASS:-mypassword}
      DB_NAME: ${DB_NAME:-mydatabase}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
      DB_SHEMA: ${DB_SHEMA:-shema}
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"



volumes:
  postgres_data: